name: Labeler

on: [pull_request]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Label
        uses: fuxingloh/multi-labeler@v1 
        with:
          config-path: .github/labeler.yml
          github-token: ${{secrets.GITHUB_TOKEN}}  