# Note when using act:
# Some services &/ steps require adjusting to test locally using `act`.
# To check for `act` use this in an if: `github.actor != 'nektos/act'`

name: Renamed workflow

on: [pull_request]

jobs:
    pre_job:
      # continue-on-error: true # Uncomment once integration is finished
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        should_skip: ${{ steps.skip_check.outputs.should_skip }}
      steps:
        - id: skip_check
          uses: fkirc/skip-duplicate-actions@master
          with:
            # All of these options are optional, so you can remove them if you are happy with the defaults
            cancel_others: 'true'
            paths_ignore: '["**/README.md"]'
            skip_after_successful_duplicate: 'true'

    test-rename:
      runs-on: ubuntu-latest
      needs: [pre_job]
      if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
      steps:
        - name: Test rename
          run: |
            echo Testing 123..

    renamed-passed:
      runs-on: ubuntu-latest
      needs: [test-rename]
      steps:
        - name: Test rename passed
          run: |
            echo Done.
