# Note when using act:
# Some services &/ steps require adjusting to test locally using `act`.
# To check for `act` use this in an if: `github.actor != 'nektos/act'`

name: Renamed workflow

on: [pull_request]

jobs:
    que:
      runs-on: ubuntu-latest
      steps:
        - uses: LouisBrunner/checks-action@v1.1.1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            name: Test XYZ
            status: "in_progress"

    test-rename:
      runs-on: ubuntu-latest
      if: |
        !contains(github.event.head_commit.message, '[skip job]')
      steps:
        - name: Test rename
          run: |
            echo Testing 123...
        - name: Github Context
          run: |
            echo "${{ toJson(github) }}"
        
    summary:
      runs-on: ubuntu-latest
      needs: [test-rename]
      if: always()
      steps:
        - uses: LouisBrunner/checks-action@v1.1.1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            name: Test XYZ
            status: "completed"
            conclusion: "success"
            output: |
              {"summary": "hello world"}
