# Note when using act:
# Some services &/ steps require adjusting to test locally using `act`.
# To check for `act` use this in an if: `github.actor != 'nektos/act'`

name: Renamed workflow

on: [pull_request]

jobs:
    test-rename:
      runs-on: ubuntu-latest
      if: ${{ contains(github.event.head_commit.message, '[skip-ci]') == false }}
      steps:
        - name: debug
          run: echo "${{ toJson(github) }}"

        - name: Test rename
          run: |
            echo Testing 123...

    passed:
      runs-on: ubuntu-latest
      if: ${{ success() }}
      steps:
        - name: Workflow was successful
          run: echo "Done. "
