# Note when using act:
# Some services &/ steps require adjusting to test locally using `act`.
# To check for `act` use this in an if: `github.actor != 'nektos/act'`

name: Renamed workflow

on: [pull_request]

jobs:
    test-rename:
      runs-on: ubuntu-latest
      steps:
        - name: Test rename
          run: |
            echo Testing 123...
        
        - uses: LouisBrunner/checks-action@v1.1.1
          if: always()
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            name: Test XYZ
            conclusion: ${{ job.status }}
            output: |
              {"summary":${{ job.status }}}