# Note when using act:
# Some services &/ steps require adjusting to test locally using `act`.
# To check for `act` use this in an if: `github.actor != 'nektos/act'`

name: Required Status

on: [push]

jobs:
    debug-context:
      runs-on: ubuntu-latest

      steps:
        - name: Github Context
          run: |
            echo "${{ toJson(github) }}"

        - name: Runner Context
          run: |
            echo "${{ toJson(runner) }}"

        - uses: actions/create-outputs@v0.0.0-fake
          id: test
        
        - uses: LouisBrunner/checks-action@v1.1.1
          if: always()
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            name: Test XYZ
            conclusion: ${{ job.status }}
            output: |
              {"summary":${{ steps.test.outputs.summary }}}