# Note when using act:
# Some services &/ steps require adjusting to test locally using `act`.
# To check for `act` use this in an if: `github.actor != 'nektos/act'`

name: Workflow chain three

on:
  workflow_run:
    types: 
      - completed
    workflows: ["Workflow chain two"]

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Echo
          run: |
            echo "This is the final part of the chain" && exit 0

    dispatch_required_status:
      runs-on: ubuntu-latest

      steps:
        - uses: octokit/request-action@v2.x
          name: Required Status Workflow Dispatch
          with:
            route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
            owner: ${{ fromJson(github.repository_owner) }}
            repo: ${{ fromJson(github.repository.name) }}
            workflow_id: "required_status"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}